-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Create Profiles Table (Public profile info)
create table profiles (
  id uuid references auth.users not null primary key,
  full_name text,
  updated_at timestamp with time zone
);

-- Create Expenses Table
create table expenses (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  amount numeric not null,
  category text not null,
  date date not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Income Table
create table income (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  amount numeric not null,
  source text not null default 'Monthly Income',
  date date not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Budgets Table
create table budgets (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  category text not null,
  amount numeric not null,
  month text not null, -- Format: YYYY-MM
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, category, month)
);

-- Create Market Prices Table (for ML training/retraining)
create table market_prices (
  id bigint generated by default as identity primary key,
  item text not null,
  price numeric not null,
  date date not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies (Row Level Security)
alter table profiles enable row level security;
alter table expenses enable row level security;
alter table income enable row level security;
alter table budgets enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

create policy "Users can view their own expenses."
  on expenses for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own expenses."
  on expenses for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own expenses."
  on expenses for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own expenses."
  on expenses for delete
  using ( auth.uid() = user_id );

-- Income RLS Policies
create policy "Users can view their own income."
  on income for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own income."
  on income for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own income."
  on income for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own income."
  on income for delete
  using ( auth.uid() = user_id );

-- Budgets RLS Policies
create policy "Users can view their own budgets."
  on budgets for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own budgets."
  on budgets for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own budgets."
  on budgets for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own budgets."
  on budgets for delete
  using ( auth.uid() = user_id );
